
[tissue]
; create uniform tissues for simulation
tissue_replace = 16 1 3 2 48 3 58 3 54 3 15 4 22 5 26 6  27 6 44 6
#
tissue_types = {  6:'cord' , 5:'csf' , 3:'applicator', 0:'default' ,1:'muscle' , 2:'bone' , 4:'tumor' }
#S/m; 
electric_conductivity    = { 'csf':2.0, 'cord':0.23 , 'applicator':2.0 ,'default':0.1  ,'muscle':0.1 , 'bone':0.02  , 'fat':0.012 , 'tumor':1.0 }
electric_conductivity_lb = { 'csf':1.0, 'cord':0.08 , 'applicator':1.0 ,'default':0.04 ,'muscle':0.04, 'bone':0.002 , 'fat':0.002 }
electric_conductivity_ub = { 'csf':3.0, 'cord':0.53 , 'applicator':3.0 ,'default':0.18 ,'muscle':0.18, 'bone':0.024 , 'fat':0.022 }
[setup]
# volts (labels)
; "applicator tip" is the centroid of the positve and negative electrodes. Should be 1.1cm  from the applicator end/tip seen in the image
voltageList = [   (2700,{'tip':58, 'entry':54, 'root':6, 'cord':6}) ]
imagefile = 'dogthree/segmentation.nii.gz'
sed = sed "s/^\s\+/dog3L3,/g;s/\s\+/,/g;s/LabelID/InstanceUID,LabelID/g;s/Vol(mm^3)/Vol.mm.3/g;s/Extent(Vox)/ExtentX,ExtentY,ExtentZ/g"  dog3L3/electric_conductivity.2700.58.54.txt > dog3L3/electric_conductivity.2700.58.54.csv
meshfile  = meshIREmidres.e
